name: CI/CD 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tesst

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-js-application:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-js-application:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest Docker image
        run: docker-compose pull

      - name: Stop & remove old container (gracefully)
        run: docker-compose down

      - name: Start new container with updated image
        run: docker-compose up -d
